### ISSUE TITLE
In-Reply-To threading

### ISSUE THREAD

**Issue by KwadroNaut** [ModernPGP/memoryhole#10]
I noticed that while using Thunderbirds' implementation of memoryhole, that threading is broken (in-reply-to is stripped). This is quite annoying for my mailflow but Iḿ a bit at loss whether the in-reply-to should be moved into the message or simply stripped or if there could be another way to deal with this. https://github.com/autocrypt/memoryhole/blob/master/guidance/README.md is a bit too shallow for me to know where to start looking.

**Comment by intrigeri** [comment]
KwadroNaut:
> I noticed that while using Thunderbirds' implementation of memoryhole, that threading is broken (in-reply-to is stripped).

According to my tests: confirmed with Enigmail 1.9.9 but this is fixed with Enigmail 2.0~beta1.

> https://github.com/autocrypt/memoryhole/blob/master/guidance/README.md is a bit too shallow for me to know where to start looking.

Yeah, "a bit too shallow" :)

**Comment by KwadroNaut** [comment]
Fixed indeed.
